.TH "colorpick" 3 "Terça, 28 de Junho de 2016" "Version 1.0" "Mini Projeto ISL29125" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colorpick \- 
.SH SYNOPSIS
.br
.PP
.SS "Estruturas de Dados"

.in +1c
.ti -1c
.RI "class \fBForm1\fP"
.br
.in -1c
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Mini Projeto ISL29125 a partir do código fonte\&.
