.TH "colorpick.Program" 3 "Terça, 28 de Junho de 2016" "Version 1.0" "Mini Projeto ISL29125" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colorpick.Program \- 
.SH SYNOPSIS
.br
.PP
.SS "Membros privados estáticos"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "\fIThe main entry point for the application\&. \fP"
.in -1c
.SH "Descrição detalhada"
.PP 
Definido na linha 9 do ficheiro Program\&.cs\&.
.SH "Documentação dos métodos"
.PP 
.SS "static void colorpick\&.Program\&.Main ()\fC [static]\fP, \fC [private]\fP"

.PP
The main entry point for the application\&. 
.PP
Definido na linha 15 do ficheiro Program\&.cs\&.
.PP
.nf
16         {
17             Application\&.EnableVisualStyles();
18             Application\&.SetCompatibleTextRenderingDefault(false);
19             Application\&.Run(new Form1());
20         }
.fi


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Mini Projeto ISL29125 a partir do código fonte\&.
