.TH "Pickcolor.X/config.h" 3 "Terça, 28 de Junho de 2016" "Version 1.0" "Mini Projeto ISL29125" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pickcolor.X/config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_XTAL_FREQ\fP   20000000"
.br
.ti -1c
.RI "#define \fBTRUE\fP   1"
.br
.ti -1c
.RI "#define \fBFALSE\fP   0"
.br
.in -1c
.SH "Descrição detalhada"
.PP 

.PP
\fBAutor:\fP
.RS 4
Leonardo & Vitor biblioteca de configuracoes gerais do PIC18F4580 
.RE
.PP

.PP
Definido no ficheiro \fBconfig\&.h\fP\&.
.SH "Documentação das macros"
.PP 
.SS "#define _XTAL_FREQ   20000000"

.PP
Definido na linha 11 do ficheiro config\&.h\&.
.SS "#define FALSE   0"

.PP
Definido na linha 13 do ficheiro config\&.h\&.
.SS "#define TRUE   1"

.PP
Definido na linha 12 do ficheiro config\&.h\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Mini Projeto ISL29125 a partir do código fonte\&.
